Repository meyfa/php-svg, pull requests merged in 2020-10, with the labels that each got.

#89 Fix string check for emptiness
  src/Writing/SVGWriter.php
  tests/Writing/SVGWriterTest.php
Labels: bug

#91 Setup PHPCS for syntax style checking
  .travis.yml
  phpcs.xml
  src/Nodes/Embedded/SVGImage.php
  src/Nodes/SVGNode.php
  src/Nodes/SVGNodeContainer.php
  src/Nodes/Shapes/SVGPolygonalShape.php
  src/Nodes/Structures/SVGDocumentFragment.php
  src/Nodes/Structures/SVGFont.php
  src/Nodes/Texts/SVGTSpan.php
  src/Nodes/Texts/SVGText.php
  src/Nodes/Texts/SVGTitle.php
  src/Rasterization/Path/ArcApproximator.php
  src/Rasterization/Path/PathApproximator.php
  src/Rasterization/Path/PathParser.php
  src/Rasterization/Path/PolygonBuilder.php
  src/Rasterization/Renderers/ImageRenderer.php
  src/Rasterization/Renderers/RectRenderer.php
  src/Rasterization/Renderers/TextRenderer.php
  src/Rasterization/SVGRasterizer.php
  src/Reading/SVGReader.php
  src/Utilities/Colors/Color.php
  src/Writing/SVGWriter.php
  tests/Nodes/Embedded/SVGImageTest.php
  tests/Nodes/SVGNodeContainerTest.php
  tests/Nodes/SVGNodeTest.php
  tests/Nodes/Shapes/SVGCircleTest.php
  tests/Nodes/Shapes/SVGEllipseTest.php
  tests/Nodes/Shapes/SVGLineTest.php
  tests/Nodes/Shapes/SVGPathTest.php
  tests/Nodes/Shapes/SVGPolygonTest.php
  tests/Nodes/Shapes/SVGPolygonalShapeTest.php
  tests/Nodes/Shapes/SVGPolylineTest.php
  tests/Nodes/Shapes/SVGRectTest.php
  tests/Nodes/Structures/SVGDefsTest.php
  tests/Nodes/Structures/SVGDocumentFragmentTest.php
  tests/Nodes/Structures/SVGStyleTest.php
  tests/Rasterization/Renderers/ImageRendererTest.php
  tests/Rasterization/Renderers/RectRendererTest.php
  tests/Rasterization/SVGRasterizerTest.php
  tests/Reading/SVGReaderTest.php
  tests/SVGTest.php
  tests/Writing/SVGWriterTest.php
Labels: enhancement, tooling

#93 Use consistent tooling config file names
  .codeclimate.yml
  .travis.yml
  phpmd.xml
  phpunit.xml
Labels: tooling

#95 Prefix Travis install with travis_retry (fixes #94)
  .travis.yml
Labels: tooling

#97 Add basic text-anchor support in renderer
  src/Nodes/Texts/SVGText.php
  src/Rasterization/Renderers/TextRenderer.php
Labels: feature

#99 Limit xdebug scope in travis
  .travis.yml
  phpunit.xml
Labels: tooling

#102 Add converter for unitless lengths during read
  src/Reading/AttributeConverter.php
  src/Reading/LengthAttributeConverter.php
  src/Reading/SVGReader.php
  tests/Reading/LengthAttributeConverterTest.php
  tests/Reading/SVGReaderTest.php
Labels: enhancement

#103 Split off node/attribute functions from SVGReader
  src/Reading/AttributeRegistry.php
  src/Reading/LengthAttributeConverter.php
  src/Reading/NodeRegistry.php
  src/Reading/SVGReader.php
  tests/Reading/AttributeRegistryTest.php
  tests/Reading/LengthAttributeConverterTest.php
  tests/Reading/NodeRegistryTest.php
  tests/Reading/SVGReaderTest.php
Labels: enhancement

#104 Make SVG dimension parameters optional
  src/Nodes/Structures/SVGDocumentFragment.php
  src/Reading/SVGReader.php
  src/SVG.php
  tests/SVGTest.php
Labels: enhancement

#105 Make SVGPolygonalShape points dynamic
  src/Nodes/Shapes/SVGPolygonalShape.php
  tests/Nodes/Shapes/SVGPolygonTest.php
  tests/Nodes/Shapes/SVGPolygonalShapeTest.php
  tests/Nodes/Shapes/SVGPolylineTest.php
Labels: enhancement

#106 Eliminate constructFromAttributes
  src/Nodes/CDataContainer.php
  src/Nodes/SVGNode.php
  src/Nodes/SVGNodeContainer.php
  src/Nodes/Structures/SVGScript.php
  src/Nodes/Structures/SVGStyle.php
  src/Reading/NodeRegistry.php
  src/Writing/SVGWriter.php
  tests/Nodes/SVGNodeContainerTest.php
  tests/Nodes/SVGNodeTest.php
  tests/Nodes/Structures/SVGScriptTest.php
  tests/Nodes/Structures/SVGStyleTest.php
  tests/Reading/SVGReaderTest.php
  tests/Utilities/SVGStyleParserTest.php
  tests/Writing/SVGWriterTest.php
Labels: enhancement

#107 Add covers annotation to all tests
  tests/Nodes/Embedded/SVGImageTest.php
  tests/Nodes/SVGNodeContainerTest.php
  tests/Nodes/SVGNodeTest.php
  tests/Nodes/Shapes/SVGCircleTest.php
  tests/Nodes/Shapes/SVGEllipseTest.php
  tests/Nodes/Shapes/SVGLineTest.php
  tests/Nodes/Shapes/SVGPathTest.php
  tests/Nodes/Shapes/SVGPolygonTest.php
  tests/Nodes/Shapes/SVGPolygonalShapeTest.php
  tests/Nodes/Shapes/SVGPolylineTest.php
  tests/Nodes/Shapes/SVGRectTest.php
  tests/Nodes/Structures/SVGDefsTest.php
  tests/Nodes/Structures/SVGDocumentFragmentTest.php
  tests/Rasterization/Path/ArcApproximatorTest.php
  tests/Rasterization/Path/BezierApproximatorTest.php
  tests/Rasterization/Path/PathApproximatorTest.php
  tests/Rasterization/Path/PathParserTest.php
  tests/Rasterization/Path/PolygonBuilderTest.php
  tests/Rasterization/Renderers/ImageRendererTest.php
  tests/Rasterization/Renderers/MultiPassRendererTest.php
  tests/Rasterization/Renderers/RectRendererTest.php
  tests/Rasterization/SVGRasterizerTest.php
  tests/Reading/AttributeRegistryTest.php
  tests/Reading/LengthAttributeConverterTest.php
  tests/Reading/NodeRegistryTest.php
  tests/Reading/SVGReaderTest.php
  tests/SVGTest.php
  tests/Utilities/Colors/ColorLookupTest.php
  tests/Utilities/Colors/ColorTest.php
  tests/Utilities/SVGStyleParserTest.php
  tests/Utilities/Units/AngleTest.php
  tests/Utilities/Units/LengthTest.php
  tests/Writing/SVGWriterTest.php
Labels: tooling

#110 Change NodeRegistry::create to use string
  src/Reading/NodeRegistry.php
  src/Reading/SVGReader.php
  tests/Reading/NodeRegistryTest.php
Labels: enhancement
